services:
  postgres:
    container_name: postgres-sql-ph
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: medical_app
    volumes:
      - postgres:/data/postgres
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5434:5432"
    networks:
      spring-ph:
        aliases:
          - postgres
    restart: unless-stopped

  ph-api:
    container_name: ph-api
    image: ph/ph:1.0.0
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/medical_app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0000
    ports:
      - "8087:8080"
    networks:
      - spring-ph
    depends_on:
      - postgres
networks:
  spring-ph:
    driver: bridge

volumes:
  postgres:
    driver: local
