name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up OpenJDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'jdkfile'
          java-version: '17'
      - name: Maven Package
        run: mvn -B clean package -DskipTests
