name: PocketHealth Backend API Pipeline

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

jobs:
  compile:
    runs-on: ubuntu-22.04
    name: Compile project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Compile project
        run: |
          ./mvnw clean compile

  build:
    runs-on: ubuntu-22.04
    name: Build backend
    needs: [compile]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Build project
        run: |
          ./mvnw clean package -DskipTests