name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build and Deploy Spring Boot application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Amazon Corretto 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml
